name: Push table_recognition_metric to pypi

on:
  push:
    # branches: [ main ]
    # paths:
    #   - 'table_recognition_metric/**'
    #   - 'docs/doc_whl.md'
    #   - 'setup.py'
    #   - '.github/workflows/gen_whl_to_pypi.yml'
    tags:
      - v*

jobs:
  UnitTesting:
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest code
        uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Unit testings
        run: |
          pip install -r requirements.txt
          pip install pytest
          pip install six
          pytest tests/test_*.py

  GenerateWHL_PushPyPi:
    needs: UnitTesting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Run setup.py
        run: |
          pip install -r requirements.txt
          pip install wheel get_pypi_latest_version

          python -m pip install --upgrade pip
          python setup.py bdist_wheel ${{ github.ref_name }}

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.UPLOAD_PYPI }}
          packages_dir: dist/
